color = input("Enter a color ")
pluralNoun = input("Enter a plural noun ")
celebrity = input("Enter a celebrity name ")
print("Roses are" , color)
print(pluralNoun +" are blue")
print("i hate" , celebrity)